{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ferrumdeck.fullname" . }}-gateway
  labels:
    {{- include "ferrumdeck.componentLabels" (dict "component" "gateway" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ferrumdeck.fullname" . }}-worker
  labels:
    {{- include "ferrumdeck.componentLabels" (dict "component" "worker" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.dashboard.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ferrumdeck.fullname" . }}-dashboard
  labels:
    {{- include "ferrumdeck.componentLabels" (dict "component" "dashboard" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}
